services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: bookstore_catalog
      MYSQL_USER: bookstore_user
      MYSQL_PASSWORD: bookstore_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bookstore_net

volumes:
  db_data:

networks:
  bookstore_net:
